include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # Add project-specific lint rules here
    prefer_const_constructors: true
    prefer_final_fields: true
    use_key_in_widget_constructors: true
