const mongoose = require('mongoose');

const eventSchema = new mongoose.Schema({
    eventId: {
        type: String, // UUID generated by the mobile app
        required: true,
        unique: true,
    },
    assetId: {
        type: String,
        required: true,
        index: true,
    },
    actionType: {
        type: String,
        enum: ['SCAN', 'STATUS_CHANGE', 'LOCATION_UPDATE', 'MAINTENANCE_LOG'],
        required: true,
    },
    payload: {
        type: Map,
        of: mongoose.Schema.Types.Mixed,
    },
    occurredAt: {
        type: Date,
        required: true, // Timestamp from the device when the event happened
    },
    syncedAt: {
        type: Date,
        default: Date.now, // Timestamp when the server received it
    },
    userId: {
        type: mongoose.Schema.Types.ObjectId,
        ref: 'User',
        required: true,
    },
    deviceId: {
        type: String,
        required: true,
    },
});

module.exports = mongoose.model('Event', eventSchema);
